# Generated by Django 6.0.7 on 2026-07-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_article_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-is_pinned', '-published_at', '-created_at'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='置顶'),
        ),
    ]
